### ISSUE TITLE
can add suport for hisi 710-980?

### ISSUE THREAD

**Issue by dengshuangjang** [penn5/hisi-idt#2]
It write the xloader.bin and fastboot.bin into hisi 655-658-659-920-925-935-960,the phone will auto reboot,and the bootloader is unlocked.This method can't unlock hisi 710-810-820-980-985-990 Bootloader,can you write a exampl for temp unlocking hisi 710 or 980 types,i need the method,could you help me?i vert like research it.

**Comment by penn5** [comment]
No.
